import 'dart:convert';
import 'dart:typed_data';

import '../models/expense_sales_log.dart';

/// Produces a portable SQL text export for this app's financial transactions.
/// The resulting file is deliberately plain SQL (not a binary SQLite file),
/// so it can be backed up, inspected, and imported again by this app.
class AppSqlExport {
  static const tableName = 'poultry_inventory_transactions';
  static const marker = 'POULTRY_INVENTORY_SQL_EXPORT_V1';

  static String buildExpenseSql(List<ExpenseSalesLog> records) {
    final out = StringBuffer();
    out.writeln('-- $marker');
    out.writeln('-- Financial transaction export generated by Poultry Inventory.');
    out.writeln('-- Daily Logs are intentionally not included in this financial export.');
    out.writeln('PRAGMA foreign_keys = OFF;');
    out.writeln('BEGIN TRANSACTION;');
    out.writeln('DROP TABLE IF EXISTS $tableName;');
    out.writeln('''CREATE TABLE $tableName (
  transaction_id TEXT NOT NULL,
  date TEXT NOT NULL,
  main_category TEXT NOT NULL,
  category TEXT NOT NULL,
  original_category TEXT NOT NULL,
  account TEXT NOT NULL,
  description TEXT NOT NULL,
  amount REAL NOT NULL,
  unit TEXT NOT NULL,
  quantity REAL NOT NULL,
  transaction_type TEXT NOT NULL
);''');

    for (final record in records) {
      final id = record.id ?? '';
      out.writeln('INSERT INTO $tableName '
          '(transaction_id,date,main_category,category,original_category,account,description,amount,unit,quantity,transaction_type) VALUES ('
          '${_quote(id)},'
          '${_quote(_date(record.date))},'
          '${_quote(record.mainCategory)},'
          '${_quote(record.category)},'
          '${_quote(record.originalCategory)},'
          '${_quote(record.account)},'
          '${_quote(record.description)},'
          '${_number(record.amount)},'
          '${_quote(record.unit)},'
          '${_number(record.quantity)},'
          '${_quote(record.transactionType)});');
    }

    out.writeln('COMMIT;');
    out.writeln('PRAGMA foreign_keys = ON;');
    return out.toString();
  }

  static String _quote(String value) => "'${value.replaceAll("'", "''")}'";

  static String _number(double value) {
    if (!value.isFinite) return '0';
    return value.toString();
  }

  static String _date(DateTime value) =>
      '${value.year.toString().padLeft(4, '0')}-'
      '${value.month.toString().padLeft(2, '0')}-'
      '${value.day.toString().padLeft(2, '0')}';

  static bool isAppSql(String text) => text.contains(marker) ||
      text.contains('CREATE TABLE $tableName');

  static String decode(Uint8List bytes) => utf8.decode(bytes, allowMalformed: false);
}
