import 'package:cloud_firestore/cloud_firestore.dart';

class NotificationTemplate {
  final String id;
  final String titleEn, titleHi, bodyEn, bodyHi;
  final bool enabled, secondReminderEnabled;
  final int reminderHour, reminderMinute, secondReminderHour, secondReminderMinute;
  const NotificationTemplate({required this.id, required this.titleEn, required this.titleHi, required this.bodyEn, required this.bodyHi, required this.enabled, required this.reminderHour, required this.reminderMinute, required this.secondReminderHour, required this.secondReminderMinute, required this.secondReminderEnabled});
  factory NotificationTemplate.fromFirestore(String id, Map<String,dynamic> d)=>NotificationTemplate(id:id,titleEn:d['titleEn']?.toString()??'',titleHi:d['titleHi']?.toString()??'',bodyEn:d['bodyEn']?.toString()??'',bodyHi:d['bodyHi']?.toString()??'',enabled:d['enabled']!=false,reminderHour:(d['reminderHour'] as num?)?.toInt()??20,reminderMinute:(d['reminderMinute'] as num?)?.toInt()??0,secondReminderHour:(d['secondReminderHour'] as num?)?.toInt()??22,secondReminderMinute:(d['secondReminderMinute'] as num?)?.toInt()??0,secondReminderEnabled:d['secondReminderEnabled']==true);
  Map<String,dynamic> toFirestore()=>{'titleEn':titleEn,'titleHi':titleHi,'bodyEn':bodyEn,'bodyHi':bodyHi,'enabled':enabled,'reminderHour':reminderHour,'reminderMinute':reminderMinute,'secondReminderHour':secondReminderHour,'secondReminderMinute':secondReminderMinute,'secondReminderEnabled':secondReminderEnabled,'updatedAt':FieldValue.serverTimestamp()};
  NotificationTemplate copyWith({String? titleEn,String? titleHi,String? bodyEn,String? bodyHi,bool? enabled,int? reminderHour,int? reminderMinute,int? secondReminderHour,int? secondReminderMinute,bool? secondReminderEnabled})=>NotificationTemplate(id:id,titleEn:titleEn??this.titleEn,titleHi:titleHi??this.titleHi,bodyEn:bodyEn??this.bodyEn,bodyHi:bodyHi??this.bodyHi,enabled:enabled??this.enabled,reminderHour:reminderHour??this.reminderHour,reminderMinute:reminderMinute??this.reminderMinute,secondReminderHour:secondReminderHour??this.secondReminderHour,secondReminderMinute:secondReminderMinute??this.secondReminderMinute,secondReminderEnabled:secondReminderEnabled??this.secondReminderEnabled);
  static const dailyReportReminder=NotificationTemplate(id:'daily_report_reminder',enabled:true,reminderHour:20,reminderMinute:0,secondReminderHour:22,secondReminderMinute:0,secondReminderEnabled:false,titleEn:'Daily Report Reminder',titleHi:'दैनिक रिपोर्ट रिमाइंडर',bodyEn:"Today's daily report for {flockName} has not been submitted.",bodyHi:'{flockName} की आज की दैनिक रिपोर्ट अभी दर्ज नहीं की गई है।');
}

class FlockNotificationSettings {
  final String languageDefault, timezone; final bool enabled,dailyReportReminder,secondReminderEnabled; final int reminderHour,reminderMinute,secondReminderHour,secondReminderMinute;
  const FlockNotificationSettings({this.languageDefault='en',this.enabled=true,this.dailyReportReminder=true,this.secondReminderEnabled=false,this.reminderHour=20,this.reminderMinute=0,this.secondReminderHour=22,this.secondReminderMinute=0,this.timezone='Asia/Kolkata'});
  factory FlockNotificationSettings.fromFirestore(Map<String,dynamic>? d){if(d==null)return const FlockNotificationSettings();return FlockNotificationSettings(languageDefault:d['languageDefault']?.toString()=='hi'?'hi':'en',enabled:d['enabled']!=false,dailyReportReminder:d['dailyReportReminder']!=false,secondReminderEnabled:d['secondReminderEnabled']==true,reminderHour:(d['reminderHour'] as num?)?.toInt()??20,reminderMinute:(d['reminderMinute'] as num?)?.toInt()??0,secondReminderHour:(d['secondReminderHour'] as num?)?.toInt()??22,secondReminderMinute:(d['secondReminderMinute'] as num?)?.toInt()??0,timezone:d['timezone']?.toString()??'Asia/Kolkata');}
  Map<String,dynamic> toFirestore()=>{'languageDefault':languageDefault,'enabled':enabled,'dailyReportReminder':dailyReportReminder,'secondReminderEnabled':secondReminderEnabled,'reminderHour':reminderHour,'reminderMinute':reminderMinute,'secondReminderHour':secondReminderHour,'secondReminderMinute':secondReminderMinute,'timezone':timezone,'updatedAt':FieldValue.serverTimestamp()};
}
